### ISSUE TITLE
bot not claim rewards

### ISSUE THREAD

**Issue by supmyhava** [vadymfedorets/CatsvsDogs#8]
Claim reward: False

**Comment by dsadwqeqeasad** [comment]
it means that it was claimed already

**Comment by supmyhava** [comment]
> it means that it was claimed already

no its not
i was in app and to check i see that i can claim
i close the app and then run the bot and he is not claim it

**Comment by dsadwqeqeasad** [comment]
because it checks if it is 8+ hours from your last claim. So if you claimed at 3:00 for example, at 8:01 you can claim it again, but script checks last claim time, not availability of claiming, because there is no api for that thing, so in this case you can claim through ui, but script wont claim because last claim was less than 8 hours ago.

**Comment by supmyhava** [comment]
> because it checks if it is 8+ hours from your last claim. So if you claimed at 3:00 for example, at 8:01 you can claim it again, but script checks last claim time, not availability of claiming, because there is no api for that thing, so in this case you can claim through ui, but script wont claim because last claim was less than 8 hours ago.

ahh ok so i will check that
thank you!
